# Generated by Django 5.2.12 on 2026-03-18 17:35

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BulkMaterialSourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=1000)),
            ],
            options={
                'ordering': [django.db.models.functions.text.Upper('name'), 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChronologicalCertainty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'chronological certainties',
                'ordering': [django.db.models.functions.text.Upper('name'), 'id'],
            },
        ),
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=1000)),
            ],
            options={
                'ordering': [django.db.models.functions.text.Upper('name'), 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeatureCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=1000)),
            ],
            options={
                'ordering': [django.db.models.functions.text.Upper('name'), 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeatureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=1000)),
            ],
            options={
                'ordering': [django.db.models.functions.text.Upper('name'), 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FlaggedItemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'flagged item statuses',
                'ordering': [django.db.models.functions.text.Upper('name'), 'id'],
            },
        ),
        migrations.CreateModel(
            name='GridSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=1000)),
                ('order', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['order', django.db.models.functions.text.Upper('name'), 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LandUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=1000)),
            ],
            options={
                'ordering': [django.db.models.functions.text.Upper('name'), 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LandUseCultivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=1000)),
            ],
            options={
                'ordering': [django.db.models.functions.text.Upper('name'), 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LandUseUncultivated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=1000)),
            ],
            options={
                'ordering': [django.db.models.functions.text.Upper('name'), 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=1000)),
            ],
            options={
                'ordering': [django.db.models.functions.text.Upper('name'), 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PotteryManufactureTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=1000)),
            ],
            options={
                'ordering': [django.db.models.functions.text.Upper('name'), 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Soil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=1000)),
            ],
            options={
                'ordering': [django.db.models.functions.text.Upper('name'), 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Spacing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=1000)),
                ('order', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['order', django.db.models.functions.text.Upper('name'), 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=1000)),
            ],
            options={
                'ordering': [django.db.models.functions.text.Upper('name'), 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=1000)),
            ],
            options={
                'ordering': [django.db.models.functions.text.Upper('name'), 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VisibilityPercentage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=1000)),
                ('order', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['order', django.db.models.functions.text.Upper('name'), 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BulkMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulk_material_id', models.CharField(db_index=True, max_length=1000, unique=True)),
                ('source_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('storage_location', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('weight', models.TextField(blank=True, null=True)),
                ('bulk_photograph', models.ImageField(blank=True, null=True, upload_to='researchdata-photographs')),
                ('bulk_observations', models.TextField(blank=True, null=True)),
                ('flagged_for_study', models.BooleanField(default=False)),
                ('flagged_for_study_reason', models.TextField(blank=True, null=True)),
                ('source_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bulk_materials', to='researchdata.bulkmaterialsourcetype')),
                ('material_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bulk_materials', to='researchdata.materialtype')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bulk_materials', to='researchdata.teammember')),
            ],
            options={
                'verbose_name_plural': '4. Bulk Material',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='GriddedCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_id', models.CharField(db_index=True, max_length=1000, unique=True)),
                ('grid_metadata_notes', models.TextField(blank=True, null=True)),
                ('grid_size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='gridded_collections', to='researchdata.gridsize')),
                ('land_use', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='gridded_collections', to='researchdata.landuse')),
                ('cultivation', models.ManyToManyField(blank=True, related_name='gridded_collections', to='researchdata.landusecultivation')),
                ('uncultivated', models.ManyToManyField(blank=True, related_name='gridded_collections', to='researchdata.landuseuncultivated')),
                ('soil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='gridded_collections', to='researchdata.soil')),
            ],
            options={
                'verbose_name_plural': '3. Gridded Collection',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='FlaggedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flagged_item_id', models.CharField(db_index=True, max_length=1000, unique=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('reason_for_flagging', models.TextField(blank=True, null=True)),
                ('flagged_item_photograph', models.ImageField(blank=True, null=True, upload_to='researchdata-photographs')),
                ('bulk_material', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='flagged_items', to='researchdata.bulkmaterial')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='flagged_items', to='researchdata.flaggeditemstatus')),
                ('material_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='flagged_items', to='researchdata.materialtype')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SurveyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_unit', models.CharField(blank=True, db_index=True, max_length=1000, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('number_of_walkers', models.IntegerField(blank=True, null=True)),
                ('bearing', models.IntegerField(blank=True, null=True)),
                ('survey_unit_metadata_notes', models.TextField(blank=True, null=True)),
                ('land_use_notes', models.TextField(blank=True, null=True)),
                ('survey_material_counted_notes', models.TextField(blank=True, null=True)),
                ('survey_material_collected_notes', models.TextField(blank=True, null=True)),
                ('survey_material_bags_collected_pottery', models.IntegerField(blank=True, null=True)),
                ('survey_material_bags_collected_tile', models.IntegerField(blank=True, null=True)),
                ('survey_material_bags_collected_lithic', models.IntegerField(blank=True, null=True)),
                ('survey_material_bags_collected_other', models.IntegerField(blank=True, null=True)),
                ('survey_material_bags_collected_notes', models.TextField(blank=True, null=True)),
                ('cultivation', models.ManyToManyField(blank=True, related_name='survey_records', to='researchdata.landusecultivation')),
                ('land_use', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='survey_records', to='researchdata.landuse')),
                ('soil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='survey_records', to='researchdata.soil')),
                ('spacing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='survey_records', to='researchdata.spacing')),
                ('uncultivated', models.ManyToManyField(blank=True, related_name='survey_records', to='researchdata.landuseuncultivated')),
                ('scribe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='survey_records', to='researchdata.teammember')),
                ('visibility_percentage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='survey_records', to='researchdata.visibilitypercentage')),
            ],
            options={
                'verbose_name_plural': '1. Survey Record',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_id', models.CharField(db_index=True, max_length=1000, unique=True)),
                ('feature_description', models.TextField(blank=True, null=True)),
                ('coordinates_recorded', models.BooleanField(default=False)),
                ('orientation', models.TextField(blank=True, null=True)),
                ('dimensions_length_cm', models.IntegerField(blank=True, null=True)),
                ('dimensions_width_cm', models.IntegerField(blank=True, null=True)),
                ('dimensions_height_cm', models.IntegerField(blank=True, null=True)),
                ('sketch', models.TextField(blank=True, null=True)),
                ('feature_metadata_notes', models.TextField(blank=True, null=True)),
                ('material_collected_pottery_quantity', models.IntegerField(blank=True, null=True)),
                ('material_collected_pottery_bags', models.IntegerField(blank=True, null=True)),
                ('material_collected_tile_quantity', models.IntegerField(blank=True, null=True)),
                ('material_collected_tile_bags', models.IntegerField(blank=True, null=True)),
                ('material_collected_lithic_quantity', models.IntegerField(blank=True, null=True)),
                ('material_collected_lithic_bags', models.IntegerField(blank=True, null=True)),
                ('material_collected_other_quantity', models.IntegerField(blank=True, null=True)),
                ('material_collected_other_bags', models.IntegerField(blank=True, null=True)),
                ('feature_condition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='features', to='researchdata.featurecondition')),
                ('feature_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='features', to='researchdata.featuretype')),
                ('survey_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='features', to='researchdata.surveyrecord')),
            ],
            options={
                'verbose_name_plural': '2. Feature',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SurveyMaterialCounted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pottery_counted', models.IntegerField(blank=True, null=True)),
                ('tile_counted', models.IntegerField(blank=True, null=True)),
                ('lithic_counted', models.IntegerField(blank=True, null=True)),
                ('other_counted', models.IntegerField(blank=True, null=True)),
                ('survey_record', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='survey_material_counteds', to='researchdata.surveyrecord')),
                ('walker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='survey_material_counteds', to='researchdata.teammember')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SurveyMaterialCollected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pottery_collected', models.IntegerField(blank=True, null=True)),
                ('tile_collected', models.IntegerField(blank=True, null=True)),
                ('lithic_collected', models.IntegerField(blank=True, null=True)),
                ('other_collected', models.IntegerField(blank=True, null=True)),
                ('survey_record', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='survey_material_collecteds', to='researchdata.surveyrecord')),
                ('walker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='survey_material_collecteds', to='researchdata.teammember')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PhotographSurveyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='researchdata-photographs')),
                ('caption', models.CharField(blank=True, max_length=1000, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('relates_to', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='photograph_survey_record', to='researchdata.surveyrecord')),
                ('photographer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='researchdata.teammember')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhotographSurveyMaterialBagsCollectedTile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='researchdata-photographs')),
                ('caption', models.CharField(blank=True, max_length=1000, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('relates_to', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='photograph_survey_material_bags_collected_tiles', to='researchdata.surveyrecord')),
                ('photographer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='researchdata.teammember')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhotographSurveyMaterialBagsCollectedPottery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='researchdata-photographs')),
                ('caption', models.CharField(blank=True, max_length=1000, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('relates_to', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='photograph_survey_material_bags_collected_potterys', to='researchdata.surveyrecord')),
                ('photographer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='researchdata.teammember')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhotographSurveyMaterialBagsCollectedOther',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='researchdata-photographs')),
                ('caption', models.CharField(blank=True, max_length=1000, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('relates_to', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='photograph_survey_material_bags_collected_others', to='researchdata.surveyrecord')),
                ('photographer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='researchdata.teammember')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhotographSurveyMaterialBagsCollectedLithic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='researchdata-photographs')),
                ('caption', models.CharField(blank=True, max_length=1000, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('relates_to', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='photograph_survey_material_bags_collected_lithics', to='researchdata.surveyrecord')),
                ('photographer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='researchdata.teammember')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhotographGriddedCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='researchdata-photographs')),
                ('caption', models.CharField(blank=True, max_length=1000, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('relates_to', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='photograph_gridded_collections', to='researchdata.griddedcollection')),
                ('photographer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='researchdata.teammember')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhotographFeatureMaterialCollectedTile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='researchdata-photographs')),
                ('caption', models.CharField(blank=True, max_length=1000, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('relates_to', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='photograph_feature_material_collected_tile', to='researchdata.feature')),
                ('photographer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='researchdata.teammember')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhotographFeatureMaterialCollectedPottery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='researchdata-photographs')),
                ('caption', models.CharField(blank=True, max_length=1000, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('relates_to', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='photograph_feature_material_collected_pottery', to='researchdata.feature')),
                ('photographer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='researchdata.teammember')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhotographFeatureMaterialCollectedOther',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='researchdata-photographs')),
                ('caption', models.CharField(blank=True, max_length=1000, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('relates_to', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='photograph_feature_material_collected_other', to='researchdata.feature')),
                ('photographer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='researchdata.teammember')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhotographFeatureMaterialCollectedLithic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='researchdata-photographs')),
                ('caption', models.CharField(blank=True, max_length=1000, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('relates_to', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='photograph_feature_material_collected_lithic', to='researchdata.feature')),
                ('photographer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='researchdata.teammember')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhotographFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='researchdata-photographs')),
                ('caption', models.CharField(blank=True, max_length=1000, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('relates_to', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='photograph_features', to='researchdata.feature')),
                ('photographer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='researchdata.teammember')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpecialistStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_id', models.CharField(db_index=True, max_length=1000, unique=True)),
                ('specialist', models.CharField(blank=True, max_length=1000, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('storage_location', models.TextField(blank=True, null=True)),
                ('pottery_object_type', models.TextField(blank=True, null=True)),
                ('pottery_decoration_technique', models.TextField(blank=True, null=True)),
                ('pottery_shape', models.TextField(blank=True, null=True)),
                ('pottery_fabric_description', models.TextField(blank=True, null=True)),
                ('pottery_flag_for_drawing', models.BooleanField(default=False)),
                ('pottery_flag_for_photography', models.BooleanField(default=False)),
                ('pottery_flag_for_sampling', models.BooleanField(default=False)),
                ('pottery_rim_diameter', models.TextField(blank=True, null=True)),
                ('pottery_base_diameter', models.TextField(blank=True, null=True)),
                ('pottery_general_dimensions', models.TextField(blank=True, null=True)),
                ('pottery_weight', models.TextField(blank=True, null=True)),
                ('pottery_start_period', models.TextField(blank=True, null=True)),
                ('pottery_end_period', models.TextField(blank=True, null=True)),
                ('pottery_comparanda', models.TextField(blank=True, null=True)),
                ('pottery_for_publication', models.BooleanField(default=False)),
                ('pottery_notes', models.TextField(blank=True, null=True)),
                ('pottery_item_returned_to_bulk', models.BooleanField(default=False)),
                ('tile_object_type', models.TextField(blank=True, null=True)),
                ('tile_part', models.TextField(blank=True, null=True)),
                ('tile_general_dimensions', models.TextField(blank=True, null=True)),
                ('tile_weight', models.TextField(blank=True, null=True)),
                ('tile_flag_for_drawing', models.BooleanField(default=False)),
                ('tile_flag_for_photography', models.BooleanField(default=False)),
                ('tile_flag_for_sampling', models.BooleanField(default=False)),
                ('tile_start_period', models.TextField(blank=True, null=True)),
                ('tile_end_period', models.TextField(blank=True, null=True)),
                ('tile_comparanda', models.TextField(blank=True, null=True)),
                ('tile_for_publication', models.BooleanField(default=False)),
                ('tile_notes', models.TextField(blank=True, null=True)),
                ('tile_item_returned_to_bulk', models.BooleanField(default=False)),
                ('lithics_object_type', models.TextField(blank=True, null=True)),
                ('lithics_material', models.TextField(blank=True, null=True)),
                ('lithics_classification', models.TextField(blank=True, null=True)),
                ('lithics_general_dimensions', models.TextField(blank=True, null=True)),
                ('lithics_weight', models.TextField(blank=True, null=True)),
                ('lithics_flag_for_drawing', models.BooleanField(default=False)),
                ('lithics_flag_for_photography', models.BooleanField(default=False)),
                ('lithics_flag_for_sampling', models.BooleanField(default=False)),
                ('lithics_start_period', models.TextField(blank=True, null=True)),
                ('lithics_end_period', models.TextField(blank=True, null=True)),
                ('lithics_comparanda', models.TextField(blank=True, null=True)),
                ('lithics_for_publication', models.BooleanField(default=False)),
                ('lithics_notes', models.TextField(blank=True, null=True)),
                ('lithics_item_returned_to_bulk', models.BooleanField(default=False)),
                ('other_object_type', models.TextField(blank=True, null=True)),
                ('other_material_or_fabric', models.TextField(blank=True, null=True)),
                ('other_material_or_fabric_description', models.TextField(blank=True, null=True)),
                ('other_general_dimensions', models.TextField(blank=True, null=True)),
                ('other_weight', models.TextField(blank=True, null=True)),
                ('other_flag_for_drawing', models.BooleanField(default=False)),
                ('other_flag_for_photography', models.BooleanField(default=False)),
                ('other_flag_for_sampling', models.BooleanField(default=False)),
                ('other_decoration', models.BooleanField(default=False)),
                ('other_descoration_description', models.TextField(blank=True, null=True)),
                ('other_manufacture', models.TextField(blank=True, null=True)),
                ('other_start_period', models.TextField(blank=True, null=True)),
                ('other_end_period', models.TextField(blank=True, null=True)),
                ('other_comparanda', models.TextField(blank=True, null=True)),
                ('other_for_publication', models.BooleanField(default=False)),
                ('other_notes', models.TextField(blank=True, null=True)),
                ('other_item_returned_to_bulk', models.BooleanField(default=False)),
                ('bulk_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='specialist_studies', to='researchdata.bulkmaterial')),
                ('flagged_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='specialist_studies', to='researchdata.flaggeditem')),
                ('lithics_chronological_certainty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='specialist_studies_lithics', to='researchdata.chronologicalcertainty')),
                ('material_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='specialist_studies', to='researchdata.materialtype')),
                ('other_chronological_certainty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='specialist_studies_other', to='researchdata.chronologicalcertainty')),
                ('pottery_chronological_certainty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='specialist_studies_pottery', to='researchdata.chronologicalcertainty')),
                ('pottery_fabric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='specialist_studies_pottery', to='researchdata.fabric')),
                ('pottery_manufacture_technique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='specialist_studies', to='researchdata.potterymanufacturetechnique')),
                ('tile_chronological_certainty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='specialist_studies_tile', to='researchdata.chronologicalcertainty')),
                ('tile_fabric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='specialist_studies_tile', to='researchdata.fabric')),
                ('tile_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='specialist_studies', to='researchdata.tiletype')),
            ],
            options={
                'verbose_name_plural': '5. Specialist Study',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='GridSquare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('square_id', models.CharField(db_index=True, max_length=1000, unique=True)),
                ('coordinates_recorded', models.BooleanField(default=False)),
                ('pottery_counted', models.IntegerField(blank=True, null=True)),
                ('tile_counted', models.IntegerField(blank=True, null=True)),
                ('lithic_counted', models.IntegerField(blank=True, null=True)),
                ('other_counted', models.IntegerField(blank=True, null=True)),
                ('pottery_collected', models.IntegerField(blank=True, null=True)),
                ('tile_collected', models.IntegerField(blank=True, null=True)),
                ('lithic_collected', models.IntegerField(blank=True, null=True)),
                ('other_collected', models.IntegerField(blank=True, null=True)),
                ('pottery_bags', models.IntegerField(blank=True, null=True)),
                ('tile_bags', models.IntegerField(blank=True, null=True)),
                ('lithic_bags', models.IntegerField(blank=True, null=True)),
                ('other_bags', models.IntegerField(blank=True, null=True)),
                ('gridded_collection', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='grid_squares', to='researchdata.griddedcollection')),
                ('land_use', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='grid_squares', to='researchdata.landuse')),
                ('soil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='grid_squares', to='researchdata.soil')),
                ('visibility_percentage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='grid_squares', to='researchdata.visibilitypercentage')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
