# Generated by Django 5.2.14 on 2026-06-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchdata', '0002_initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyunitmaterialscountedandcollected',
            name='lithic_collected',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='surveyunitmaterialscountedandcollected',
            name='lithic_counted',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='surveyunitmaterialscountedandcollected',
            name='other_collected',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='surveyunitmaterialscountedandcollected',
            name='other_counted',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='surveyunitmaterialscountedandcollected',
            name='pottery_collected',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='surveyunitmaterialscountedandcollected',
            name='pottery_counted',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='surveyunitmaterialscountedandcollected',
            name='tile_collected',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='surveyunitmaterialscountedandcollected',
            name='tile_counted',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
